export const TOGGLER_BTN = ".floating-chat__toggler"
export const DIALOG = ".floating-chat__dialog"
export const CLOSE_BTN = ".floating-chat__close-btn"
export const USER_MESSAGE_FORM = ".floating-chat__user-message"
export const USER_MESSAGE_INPUT = ".floating-chat__user-message textarea"